# Target .pde file
TARGET = 

# List of Arduino libraries that need to be included (e.g. LIBRARIES = EEPROM Matrix)
LIBRARIES = 

# Type of unit (either atmega8 or atmega168)
MCU = atmega168

include Makefile.common.include
include Makefile.$(MCU).include
